-- phpMyAdmin SQL Dump
-- version 5.2.0-1.el7.remi
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 29-04-2023 a las 04:03:54
-- Versión del servidor: 10.4.28-MariaDB
-- Versión de PHP: 7.4.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `biokudi`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `lugares`
--

CREATE TABLE `lugares` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(255) NOT NULL,
  `DIRECCION` varchar(255) NOT NULL,
  `COORDENADAS` varchar(255) NOT NULL,
  `ACTIVIDAD` varchar(1000) NOT NULL,
  `DESCRIPCION` varchar(1000) NOT NULL,
  `INFORMACION` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Volcado de datos para la tabla `lugares`
--

INSERT INTO `lugares` (`ID`, `NOMBRE`, `DIRECCION`, `COORDENADAS`, `ACTIVIDAD`, `DESCRIPCION`, `INFORMACION`) VALUES
(3, 'Laguna de Guatavita ', 'Laguna de Guatavita, Sesquilé, Cundinamarca', '4.977521, -73.775038', 'Mirador, caminata por sendero.', 'Laguna sagrada de la cultura precolombina, en ella se escenificaba el legendario rito de El Dorado. ', 'En la fauna se pueden encontrar zorros y mirlas de páramo.\r\nDentro de la flora del lugar encontramos frailejones, atrapamoscas, curubos silvestres, entre otros. \r\n\r\nhttp://www.colparques.net/LGUATAVITA#aceptar '),
(4, 'Parque ecoturístico Santuario Chiquito', 'Tausa y, Kilómetro 28 vía Zipaquirá, San Cayetano, Pacho, Cundinamarca', '5.198348, -74.029621', 'Caminatas ecológicas, montañismo, ciclo paseos, restauración ecológica, camping y rally fotográfico.', 'Es una reserva natural que ofrece vistas impresionantes del valle del Magdalena y la región de Pacho. Cuenta con importantes sectores de bosque de niebla y se destaca por sus formaciones rocosas.', 'Hermosos paisajes con cascadas, lagunas, acantilados, flora y fauna de páramo, formaciones rocosas, cumbres puntiagudas y valles inundados de frailejones.\r\nhttps://caminantesdelretorno.com/destino/santuario-chiquito/'),
(5, 'Parque Natural Chicaque', 'Vía Soacha, Km. 8, Soacha, Mosquera, Cundinamarca', '4.606504, -74.304797', 'Arborismo, tirolinea, cabalgata, caminata nocturna, senderismo, alojamiento, avistamiento de aves.', 'El parque resguarda especies de flora y fauna únicas en el mundo, y es el hogar de más de 100 especies de aves y alrededor de 20 especies de mamíferos.', 'Habitan cientos de especies de aves y mamíferos como perezosos, tigrillos, guatines, borugos, micos nocturnos y puercoespines. Son fuente de agua pura para San Antonio del Tequendama.\r\nhttps://www.chicaque.com/'),
(6, 'Hacienda Coloma', 'Av. las Palmas Vía Tibacuy, Fusagasugá, Cundinamarca', '4.343180,-74.377357', 'Recorridos del proceso de cultivo y producción del café.', 'Hacienda que enseña el proceso completo de producción del café, desde su semilla hasta la esencia de cada sorbo.', 'https://www.haciendacoloma.com.co/'),
(7, 'Reserva natural Peña del Aserradero', 'Albán, Cundinamarca', '4.880088, -74.435848', 'Senderismo, escalada y avistamiento de aves.', 'Sendero de 1200 metros dentro de un bosque nuboso. Esta ubicada dentro de un corredor Andino para la conservación de la biodiversidad en los relictos del bosque y el  abastecimiento hídrico.', 'Se destaca el colibrí endémico y amenazado conocido como Blck Inca. Otras especies de interés como el Torito esmeralda, el Trepatroncos perlado, el chamicero endémico coliplata, el Atrapamoscas barrado y la Tangara de cejas verdes.\r\nhttps://www.facebook.com/events/alb%C3%A1n-cundinamarca/aventura-camino-ecol%C3%B3gico-pe%C3%B1as-del-aserradero-alb%C3%A1n/412263052440842/'),
(8, 'Parque Aventura La Chorrera', ' Parque Aventura La Chorrera, Choachí, Cundinamarca', '4.587434, -73.951216', 'Rapell guiado, torrentismo guiado, zona de camping, gastronomia de la región, puente tibetano, canopy, puente indiana jones, aviturismo, cascadas.', 'Experiencias ecoagroturisticas y turismo de aventura con la intensión de generar espacios de reconocimiento cultural por medio de la riqueza natural.', 'https://lachorrera.com.co/quienes-somos/'),
(9, 'Tygüa Magüe Ecoparque', 'Vda. Lourdes, Tabio, Cundinamarca', '4.919866, -74.077877', 'Caminatas ecológicas y paisajismo rural, yoga, meditación, senderismo, avistamiento de aves y camping.', 'Ubicada en las montañas de Tabio, es un lugar para la educación ambiental y la investigación científica, con programas para la conservación de especies en peligro de extinción y proyectos de reforestación.', 'El ecoparque cuenta con programas de conservación de especies en peligro de extinción, como el oso andino, el cóndor andino y el tigrillo. \r\nhttps://tygua-mague-ecoparque.negocio.site/'),
(10, 'Piedra Colgada', 'Finca Piedra colgada, Vereda, El Tablon, Susa, Cundinamarca', '5.425196, -73.846210', 'Caminata', 'Finca que queda en una vereda, en ella se pueden hacer caminatas.', 'Mirador hacia la laguna de Fúquene y alrededores, antiguo Camino Empedrado\r\nFarallones de Susa y Carupa. \r\nhttps://ecoglobalexpeditions.com/caminata-ecologica-piedra-colgada/'),
(11, 'Bioparque La Reserva', 'Vereda el Abra Km 1,2, Cota, Cundinamarca', '4.808084, -74.116972', 'Recorrido, inmersión en ecosistemas, auditorio temático, reconocerás las consecuencias e impacto del tráfico ilegal de fauna silvestre en nuestra biodiversidad.', 'Conservación de fauna silvestre colombiana, flora y recursos naturales a través de proyectos de educación ambiental e investigación sobre biodiversidad de ecosistemas colombianos.', 'Plantas carnivoras, diferentes especies, \r\nhttps://www.bioparquelareserva.com/proyectos/'),
(12, 'Parque de Las Orquídeas del Tequendama', 'kilometro 19 via bogota el colegio, San Antonio Del Tequendama, Cundinamarca', '4.590799, -74.351327', 'Visita guiada y avistamiento de aves.', 'Destino natural que ofrece a sus visitantes un paseo con deliciosos aromas, colores y formas en el reino de las flores más exóticas del mundo.', 'Las orquídeas en su variedad inagotable se exponen en los troncos de los árboles, o sobre rocas. Además hay una   amplia colección de heliconias, bromelias y plantas ornamentales, que forman un jardín, recreado por pájaros y mariposas.\r\nhttps://www.orquideasdeltequendama.com/'),
(13, 'Agro Parque Sabio Mutis', 'Tena, La Mesa, Cundinamarca', '4.623500, -74.429887', 'Visitas guiadas, talleres de jardinería, observación de aves, senderismo y picnic.', 'El parque cuenta con exhibiciones interactivas y educativas que muestran la importancia de la agricultura sostenible y la conservación de la biodiversidad.', 'Con más de 40 hectáreas de tierra y alrededor de 7.000 variedades de plantas, entre ellas las orquídeas, cactus y suculentas, hortalizas y plantas medicinales.\r\nhttps://www.uniminuto.edu/agroparque-sabio-mutis'),
(14, 'Rocas de Suesca', 'Av 15#103-70 Bogotá Vereda Cacicazgo Frente a estación de trén, Suesca, Cundinamarca', '5.117163, -73.794132', 'Escalar, caminatas.', 'Las rocas de Suesca corresponden a la roca sedimentaria tipo arenisca. La roca ofrece buena adherencia para escalar.', 'http://www.colparques.net/SUESCA#aceptar'),
(15, 'Laguna de Fúquene', 'Fúquene, Cundinamarca', '5.468890, -73.744732', 'Pesca deportiva, el senderismo, la observación de aves y la práctica de deportes náuticos como el kayaking y el paddleboard.', 'Es un cuerpo de agua dulce. Posee numerosas islas, una de ellas fue santuario de los muiscas.', 'Entre las especies se encuentran el pato zambullidor, el pato real, la gallareta, el pelícano, el halcón peregrino, y la especie endémica de pez llamada blanquillo de Fúquene.\r\nhttps://oaica.car.gov.co/vercaso.php?id=241 '),
(16, 'Observatorio de Colibríes', 'Variante Frailejonal, La Calera, El Cerrito, La Calera, Cundinamarca', '4.664592, -73.964449', 'Observación de colibries.', 'Un refugio seguro y una fuente de alimento para el sustento y reproducción de los colibries.', 'https://www.observatoriodecolibries.com/visits'),
(17, 'Parque Nacional Natural Chingaza', 'Parque Nacional Natural Chingaza, La Calera, Cundinmarca', '4.547703, -73.733354', '6 Senderos ecoturísticos: Cuchillas de Siecha, Lagunas de Buitrago, laguna seca\r\nSuasie (sector Monterredondo), Las Plantas del Camino-Laguna de Chingaza, Lagunas de Siecha (entrada por el municipio de Guasca).', 'Actualmente es un remanso de fauna y flora andina, revelando al visitante el secreto de la vida.', 'Los ecosistemas altoandinos, bosques subandinos y páramos predominan en la zona, actuando además como refugio de majestuosas reservas de fauna y flora.\r\nhttps://www.parquesnacionales.gov.co/portal/en/ecotourism/orinoco-region/chingaza-national-natural-park/'),
(18, 'Laguna El Tabacal ', 'Via Laguna el Tabacal, La Vega, Cundinamarca', '5.026122, -74.328299', 'Caminatas ecológicas, senderismo, contemplar la laguna, la fauna y flora, avistamiento de aves.', 'Lo que atrae a muchos a la laguna es la sinfónica melodía que exhiben las más de 400 especies aves reportadas en el sitio, considerándose como el tercer lugar de avistamiento de aves para Colombia', 'Avistamientos de aves: el cormorán neotropical que surca las aguas de la laguna en busca de alimento o el atrapamoscas de pecho amarillo con su característico canto.\r\nhttps://caminatasecologicasbogota.com/laguna-el-tabacal/'),
(19, 'Cascada La Chorrera', 'Choachí, Cundinamarca', '4.597420, -73.9599860', 'Caminatas.', 'Es considerada la cascada más alta del país con una altura de 590 metros y es uno de los atractivos turísticos más visitados de la región.', 'Bosque de niebla con orquídeas, bromelias y cientos de especies de aves.\r\nhttps://www.roadtrip.travel/roadtrips/caminando-por-un-bosque-de-niebla-a-la-cascada-la-chorrera-la-mas-alta-de-colombia'),
(20, 'Centro Comercial Centro Chia', 'Av. Pradilla # 9-00 East, Chía, Cundinamarca', '4.865861, -74.036504', 'Espacio natural.', 'Centro Comercial Naturalmente Único que cuenta con más de 25.000 mts de parque natural en donde encontrarás caminos verdes que te llevarán a explorar aves, peces, patos, tortugas.', 'https://www.centrochia.com.co/parque/'),
(21, 'Jardín Encantado: Observatorio de Colibríes', 'Finca la tortuguita en San Francisco, Cundinamarca ', '4.978893, -74.293357', 'Observación del colibrí.', 'Atrae más de 25 especies de colibríes de las 165 que han sido clasificadas en Colombia. Este lugar es un punto de referencia para los ornitólogos, fotógrafos especializados, ambientalistas y amantes de la naturaleza. ', 'https://www.jardinencantado.net/#services'),
(22, 'Parque Arqueológico Piedras del Tunjo', 'Cl. 5, Facatativá, Cundinamarca', '4.816296, -74.346265', 'Caminata.', 'Se encuentran abrigos rocosos con un sinnúmero de pinturas rupestres que conforman un importante patrimonio arqueológico.  ', 'http://www.colparques.net/FACA#aceptar'),
(23, 'Reserva Natural El Chochal de Siecha', 'Vda. La Trinidad, Guasca, Cundinamarca', '4.805952, -73.887662', 'Paseo en la laguna, caminatas, avistamiento de aves, cabalgata.', 'Un lugar ideal para estar en contacto con naturaleza, armando recorridos.', 'https://elchochaldesiecha.com/'),
(24, 'Truchas El Abuelo', 'la y, lago timana, vereda el salitre, Guasca, Cundinamarca', '4.823780, -73.935774', 'Visitas guiadas a las piscifactorías y pesca deportiva.', 'Restaurante ubicado a 45 minutos de Bogotá vía sopo o vía la calera,  se cultivan truchas en piscifactorías y se venden frescas o preparadas en diferentes platos de la gastronomía local.', 'https://truchaselabuelo.com/'),
(25, 'Parque Ecológico Rancho Los Leones', 'Vía La Vega - Sasaima #13, La Vega, Cundinamarca', '4.998677, -74.339630', 'Paseos a caballo, senderismo, piscinas, pesca, deportes de campo', 'Una finca de recreación familiar ubicada en la región de Cundinamarca, cerca de la ciudad de Bogotá.', 'https://www.rancholosleones.com/'),
(26, 'Sendero Ecológico La Cascada', '253207, Albán, Cundinamarca', '4.894798, -74.437380', 'Caminatas.', 'Esta finca cuenta con un sendero ecológico que conduce a una hermosa cascada.l Se puede apreciar una gran variedad de plantas y animales, incluyendo aves y mariposas. ', 'https://granjacascada.jimdofree.com/'),
(27, 'Parque Tematico Cafetero Finca la Pedregoza', 'Santandercito - San Antonio De Tequendama #5, San Antonio Del Tequendama, Cundinamarca', '4.595592, -74.341129', 'Senderismo y avistamiento de aves', 'Un espacio con sabor a café y con el ritmo de los cantos de las aves mas hermosas. Ofrece a los visitantes la oportunidad de experimentar la vida en el campo, aprender sobre la agricultura sostenible y disfrutar de la naturaleza.', 'https://fincalapedregoza.co/parque-tem%C3%A1tico-cafetero'),
(28, 'Parque Natural Los Tunos', 'Troncal del Tequendama, km 11.8, Vda. Arracachal, San Antonio Del Tequendama, Cundinamarca', '4.566895, -74.318221', 'Avistamiento de aves y senderismo.', 'Reserva natural que hace parte del cinturón de bosque de niebla mejor conservado del valle del río Magdalena en pleno corazón del país.', 'Cuenta con un proyecto de conservación del bosque de Niebla y aves como: Torcaza Collareja, Turpial Montañero, Azulejo Montañero y Tangara de Lentejuelas.\r\nhttps://lostunos.com.co/\r\n'),
(29, 'Mirador de la Laguna de Suesca', 'Vereda Ovejeras, Suesca, Cundinamarca', '5.194765, -73.765709', 'Caminatas, camping, paseo en bote, escalada en roca y pesca deportiva.', 'Este mirador ofrece una vista panorámica de la Laguna de Suesca, el cual es un cuerpo de agua natural que se encuentra en una zona montañosa rodeada de bosques y senderos.', 'https://mirador-de-la-laguna-de-suesca.negocio.site/'),
(30, 'Desierto de Sabrinsky', 'Mosquera, Cundinamarca', '4.666550, -74.285454', 'Caminatas.', 'Las condiciones climáticas son áridas, en su suelo la lluvia es escasa. Se encuentra ubicado en un terreno rocoso ofreciendo un paisaje exótico por el colorido de la tierra que pasa de rojo intenso a terracotas y naranja.', 'http://mosqueracundinamarca.micolombiadigital.gov.co/turismo/desierto-mondonedo-o-sabrinsky'),
(31, 'Guandalay Ecoparque Ancestral', 'Vereda Quebrada Grande, San Antonio Del Tequendama, Cundinamarca', '4.608985, -74.365305', 'Observación de aves, caminatas interpretativas y actividades al aire libre para equilibrar la energía del cuerpo', 'Lugar de contemplación y apreciación de la naturaleza. ', 'https://www.guandalay.xyz/'),
(32, 'Lagunas de Siecha', 'Guasca, Cundinamarca', '4.765984, -73.852778', 'Caminatas.', 'Son un conjunto de lagunas ubicadas en el Parque Nacional Natural Chingaza, en la Cordillera Oriental de los Andes colombianos.', 'https://montanascolombianas.com/siecha-lakes-1-day/?lang=en'),
(33, 'Piedras Del Chivo Negro', 'Bojacá, Cundinamarca', '4.716965, -74.324486', 'Senderismo por el parque, Bouldering (practica de escalada en roca pequeña), montar en Bicicleta y también acampar.', 'Un sitio arqueológico que alberga una serie de petroglifos precolombinos tallados en rocas que tienen formas abstractas y geométricas, y se cree que fueron hechos por los muiscas.', 'https://sitiosdeturistas.blogspot.com/2020/02/piedras-de-chivo-negro.html'),
(34, 'Finca Agroecológica Nigayala', 'km. 10 Finca la reserva Vereda, Jerusalén, La Calera, Cundinamarca', '4.678170, -73.928424', 'Caminatas y huerta natural', 'Cabañas rústicas en madera, con chimenea y energía solar, rodeado de naturaleza y montaña, en una finca ecológica', 'https://www.tripadvisor.es/Attraction_Review-g1222951-d12548015-Reviews-Finca_Agroecologica_Nigayala-La_Calera_Cundinamarca_Department.html'),
(35, 'Café Jaguar Finca La Esperanza', 'Altos de Yayatá, Silvania, Cundinamarca', '4.418350, -74.389222', 'Caminatas, y degustación de café', 'Finca productora de café exótico colombiano. ', 'https://jaguarcoffeeonline.com/'),
(36, 'Boquemonte Reserva Natural', 'Km 4.8, Variante Soacha - La Mesa Rural, Soacha, Cundinamarca', '4.606920, -74.297002', 'Senderismo, camping, picnic, avistamiento de aves y deporte de aventura.', 'Se encuentran en una de las mejores zonas rurales de preservación ecológica del país con más de 1500 especies de flora y fauna y con el inigualable clima Bosque de niebla ó Bosque Alto Andino.', 'Es el hogar de una gran variedad de especies animales y vegetales, muchas de ellas en peligro de extinción, como el oso hormiguero, el jaguar, el cóndor de los Andes y el guanaco.\r\nhttps://boquemonte.com/'),
(37, 'Embalse del Neusa', 'Neusa - San Cayetano, Cogua, Cundinamarca', '5.135917, -73.967913', 'Pesca deportiva, deportes acuáticos, navegación y ciclo montañismo. ', 'Dentro del área del parque se desarrollan ambientes especiales para el hábitat de diferentes especies de fauna y animales silvestres, además de gran cultivo de truchas que se pueden pescar. ', 'Este paraíso natural tiene una extensión de bosque andino con plantaciones forestales de pino, eucalipto y bosque nativo y un embalse con especies de peces como la trucha arco iris, el capitán de la sabana y la guapucha.\r\nhttp://www.colparques.net/NEUSA#aceptar'),
(38, 'Cascadas del Chupal', 'Cascadas del Chupal, La Vega, Cundinamarca', '5.045438, -74.306864', 'Camping, Caminatas, Torrentismo y el disfrute de las bellas cascadas.', 'Son 4 cascadas, para hacer la caminata es necesario contar con un buen estado físico, ropa cómoda y zapatos de buen agarre, ya que hay varios transectos con altas pendientes y lisos por las piedras.', 'https://mujerforestal.com/cascadas-del-chupal-la-vega-cundinamarca/'),
(39, 'Parque Ecológico Carmen De Los Juncales', 'Parque Ecológico Carmen De Los Juncales, Tabio, Cundinamarca', '4.932913, -74.111626', 'Caminata', 'Parque ecológico donde se hacen recorridos, observando la recuperación de biodiversidad en la región sabanera.', 'https://www.fueradelarutina.com/planes-para-hacer-en-tabio/parque-ecologico-carmen-de-los-juncales/'),
(40, 'Cascada de Nemosten-Sueva', 'Cascada de, Nemosten, Junín, Cundinamarca', '4.810974, -73.733441', 'Caminata, mirador. ', 'Cascada de Sueva que se encuentra en la vereda Nemusten municipio Junin inspección de Sueva, Cascadas cerca a Bogotá.', 'Las rutas diseñadas y ofrecidas por Conexión Natural están clasificadas acorde a 5 niveles de dificultad. \r\nhttps://caminatasecologicasbogota.com/cascada-de-sueva/'),
(41, 'Embalse del Guavio', 'Cl. 4 #31, Gachalá, Cundinamarca', '4.695557, -73.509249', 'Deportes náuticos, caminatas, cabalgata.', 'Es una central hidroeléctrica, aunque fue construida para generar la energía que abastece gran parte del país, hoy es un gran atractivo turístico, por ser escenario de diferentes actividades recreativas. ', 'https://elturismoencolombia.com/a-donde-ir/cundinamarca-colombia-travel/embalse-guavio-gachala-cundinamarca/'),
(42, 'Mirador Piedra Capira', '50, Guaduas, Cundinamarca', '5.090303, -74.635073', 'Recorrido mirador', 'Entre los lugares que se pueden contemplar desde el Mirador de la Piedra Capira encontramos el rio Magdalena y los nevados del Ruiz, Santa Isabel y Tolima, además de varios municipios como Mariquita, Ambalema y Honda.', 'Los visitantes que deseen hacer el recorrido a pie, pueden hacerlo en una caminata de aproximadamente una hora por el camino real.\r\nhttps://portavozdigital.com/mirador-piedra-capira-guaduas/'),
(43, 'Reserva Ecopalacio Chingaza', 'Vda. La Trinidad, Guasca, Cundinamarca', '4.742241, -73.850906', 'Senderismo y caminatas.', 'Una experiencia exclusiva, personalizada y completa en el Páramo de Chingaza, donde te sumergirás en el ecosistema de páramo.', 'Acercamiento a la fauna local, entre ellas: el oso de anteojos, aves como el barbudito de páramo, o venados de cola blanca.\r\nhttp://ecopalaciochingaza.co/'),
(44, 'Camping Montañero', 'Cl. 14d #8-27, Facatativá, Cundinamarca', '4.822156, -74.358002', 'Senderismo, campin, y travesías.', 'Campamentos y expediciones temáticas que contribuyen al fortalecimiento de habilidades blandas y a la conexión con la riqueza natural, cultural e histórica del departamento de Cundinamarca', 'https://www.campingmontanero.com/'),
(45, 'Reserva Natural El Zoque', 'Km 6.5 Via Guasca - Gacheta, Vereda Pastor Ospina 57 Guasca, Cundinamarca', '4.850441, -73.835817', 'Largas caminatas para descubrir el Páramo hasta actividades y talleres de siembra de fauna nativa.', 'Esta ubicada en el páramo de Guasca a una hora de Bogotá. A 6.5 kilómetros del pueblo de Guasca vía Gachetá se encuentra la Reserva El Zoque.', 'Su principal objetivo es la recuperación de las cuencas del páramo, implementando un vivero de especies nativas.\r\nhttps://www.reservaelzoque.co/\r\n'),
(46, 'Granja Guacamaya', 'Guacamaya, Chipaque, Cundinamarca', '4.43051, -74.07570', 'Cabalgatas, caminatas ecológicas, aguas termales, pesca deportiva', 'Granja familiar lleno de naturaleza muy cerca a Bogotá, en el municipio de Chipaque Cundinamarca.', 'https://granjaguacamaya.com/'),
(47, 'Finca Ecoturística Mirador De San Antonio', 'Vereda La Escuela, Tibacuy, Cundinamarca', '4.34768, -74.45230', 'Avistamiento panorámica del Sumapaz y zona de camping', 'Proyecto familiar turístico y lugar ideal para disfrutar de la naturaleza y la belleza escénica de la región.', 'https://www.facebook.com/MiradorSAntonio/'),
(48, 'Termales Santa Mónica', 'Vereda Resguardo km 2, Choachí, Cundinamarca', '4.549078, -73.917113', 'Ofrecen servicios de spa, masajes y piscinas termales.', 'Emplazado en las laderas de la Cordillera Oriental de los Andes, este paraíso natural cuenta con aguas termales medicinales que proveen a piscinas, jacuzzi, salas de sauna y turco.', 'https://www.termalessantamonica.com/'),
(49, 'Bosque Ecuestre & Valle del Pony', 'Vereda Meusa Sopó, Km 10 vía Sopó La Calera, Sopó, Cundinamarca', '4.843097, -73.934001', 'Vaulting (Gimnasia al lomo del caballo), adiestramiento de caballos, clases de equitación y paseo Ecuestre.', 'Escuela de Equitación enfocada en el amor por los Caballos y la Naturaleza con una vista sobre la Sabana.', 'https://www.facebook.com/bosquecuestre/'),
(50, 'La Isabela Centro Ecuestre', '0000 Vereda Santa bárbara centro, Tabio, Cundinamarca', '4.932045, -74.092320', 'Ofrece servicios de entrenamiento y paseos a caballo, rutas de cabalgata y eventos ecuestres ', 'Escuela de equitación lugar de inspiración y recursos para los amantes de los caballos y la equitación en Colombia.', 'https://www.instagram.com/isabelaecuestre/?hl=es'),
(51, 'El Gran Pozo Azufrado', 'Km 3.5, Jerusalén - Tocaima, Tocaima, Cundinamarca', '4.481051, -74.648493', 'Lodoterapia (actividad relajante donde se usa el barro medicinal azufrado), servicio de piscinas recreacionales, museo paleontológico y arqueológico, y caminatas ecológicas con las que cuenta el parque natural.', 'Centro vacacional familiar con la naturaleza, certificado con las aguas azufradas y el lodo medicinal Azufrado.', 'Barro medicinal Azufrado que se puede encontrar en la fuente natural Acuata.\r\nhttps://www.facebook.com/ElGranPozoAzufrado/?locale=es_LA'),
(52, 'Los Pocitos Azufrados de Tocaima', 'km 3, Jerusalén - Tocaima, Jerusalén, Cundinamarca', '4.479141, -74.645806', 'Hidroterapia y servicio de restaurante.', 'Centro recreacional que cuenta con pozos de agua y lodo azufrados, poseedores de excelentes propiedades medicinales, terapéuticas, y cosméticas', 'Lugar de aguas medicinales y barros azufrados.\r\nhttps://www.facebook.com/LosPocitosAzufrados/?locale=es_LA'),
(53, 'Kalú Night Picnic Theater', 'VXC6+VM, Chía, Cundinamarca', '4.87243, -74.03835', 'Experiencia única de teatro al aire libre, el disfrute de la naturaleza y el arte en armonía.', 'Una compañía teatral con sede en Colombia que se especializa en espectáculos de teatro de picnic', 'https://www.instagram.com/kalu_picnictheater/?hl=es'),
(54, 'Barlovento Travesías en Velero', 'Embalse de Tominé, Guatavita, Cundinamarca', '4.943209 , -73.843838', 'Paseos en velero y experiencias de navegación de varios días.', 'Es un lugar ideal para disfrutar de la naturaleza y navegar en velero por el Embalse de Tominé.', '\r\nhttps://barloventopaseosenvelero.com/ '),
(55, 'Kombai Park Montearroyo', 'Parque Tématico de Aventura, Km 30 Via, Bogotá-La Vega, La Vega', '4.899270, -74.310365', 'Recorridos de cuerdas altas, escalada en roca y en árbol, cauchera humana, circuitos de tirolesas, saltos de caída libre, bungee trampolín, recorridos de slackline, pesca deportiva, caminatas ecológicas, camping.', 'Parque temático en un terreno grandioso cuya topografía entrega grandes opciones de diversión y ocupación de tiempo en familia.', 'https://kombaipark.com/'),
(56, 'La Bandolera Trailrides', 'Via San Vicente, Suesca, Cundinamarca', '5.072293, -73.775852', 'Cabalgatas a través de bosques, senderos y paisajes.', 'Una hacienda que nace del amor a los animales, el campo y los viajes de a caballo y a lomo de mula.', 'https://labandolera.com/'),
(57, 'Termales Los Volcanes', 'Km 13 vía, El Sisga - Macheta, Chocontá, Cundinamarca', '5.092886, -73.640661', 'Masajes, spa y acceso a las aguas termales.', 'Una empresa dedicada al bienestar por medio de aguas termales que se destacan por sus grandes propiedades y un complejo eco turístico.', 'Rodeado de naturaleza enmarcado por las imponentes montañas del paisaje cundinamarqués\r\nhttps://termaleslosvolcanes.com/'),
(58, 'Termales Aguas Calientes Guasca', '251218, Vda. Santuario, Guasca, Cundinamarca', '4.876155, -73.857844', 'Ofrece servicios de relajación y turismo en una zona rodeada de naturaleza y aguas termales.\r\n', 'Complejo turístico con piscinas termales, áreas de descanso, restaurantes, zonas de camping y alojamiento en cabañas y habitaciones.', 'https://www.instagram.com/termalesguasca/?hl=es-la'),
(59, 'Suescalada', 'Cra. 23 #53A-05 3er piso, Teusaquillo, Bogotá, Cundinamarca', '4.64234, -74.07352', 'Escalada, senderismo, ciclismo de montaña y parapente.', 'Destino popular para los amantes de la escalada en roca en Colombia. Cuenta con numerosos riscos y paredes de roca natural que son ideales para la escalada deportiva y tradicional.', 'En cuanto a la flora y fauna, cuenta con especies nativas, incluyendo aves como el cóndor andino, el búho y el colibrí, y animales como zorros, armadillos y serpientes.\r\nhttps://www.suescalada.com/'),
(60, 'Club Trango Aventura', 'Cra. 5, Suesca, Cacicazgo, Suesca, Cundinamarca', '5.091861, -73.792082', 'Escalada En Roca, Caminatas, Yoga, Rappel y Carpas Aéreas.', 'Agencia de viajes por Colombia, Perú, Bolivia, Estados Unidos, Nepal y mucho más.', 'https://www.facebook.com/clubtrangoaventura/'),
(61, 'Termales El Zipa', 'Tabio, Cundinamarca', '4.923420, -74.104710', 'Ofrece baños turcos, jacuzzis y piscinas termales.', 'Fuentes de aguas termales y recurso natural unido a la historia ancestral del lugar que con sus minerales activos proporciona beneficios medicinales, en su agradable destino para relajarse y disfrutar sumergido en sus cálidas aguas rodeadas de naturaleza.', 'Eran fuentes de agua para la comunidad Chibcha donde el cacique y su sequito descansaban.\r\nhttp://www.tabio-cundinamarca.gov.co/turismo/termales-el-zipa '),
(62, 'Termales Aguas Calientes', '251218, Vda. Santuario, Guasca, Cundinamarca', '4.876154, -73.857845', 'Caminatas y baños en las termales.', 'Cuenta con fenómenos como agua a 75 ºC, baños a vapor, un nacimiento de petróleo y la cascada que tiene una conformación rocosa.', 'Especies nativas, incluyendo aves como el tucán y el colibrí, así como mamíferos como el zorro y el oso hormiguero.\r\nhttps://www.covioriente.co/termales-aguas-calientes-area-protegida-donde-podra-disfrutar-de-una-experiencia-natural/ '),
(63, 'A Pata con Joaco Punto de Atención', 'Cra. 5 #6-57, Villeta, Cundinamarca', '5.01272, -74.47039', 'Senderismo, caminatas, canyoning, rafting, canopy y paintball.', 'Servicio de guías turísticos para quienes desean conocer los atractivos locales.', 'http://apataconjoaco.com/ '),
(64, 'Cabalgatas Trote & Galope', '251201, La Calera, Cundinamarca', '4.716914, -73.978629', 'Cabalgatas.', 'Agencia de turismo dedicada a promocionar y ofrecer servicios de paseos a caballo en la región', 'https://www.instagram.com/cabalgatastroteygalope/?hl=es'),
(65, 'Senda Nativa Naturaleza y Aventura', 'Cra. 1 #250, Guatavita, Guasca, Cundinamarca', '4.912791, -73.897195', 'Caminatas, ciclo montañismo, aventura en cuatrimoto, parapente en Guatavita, veleros y senderismo.', 'Un pueblo con hermosas casas blancas con techos en barro cocido y una arquitectura colonial. Frente a este pueblo el embalse de Tominé, una hermosa represa de agua rodeada de montañas. y a 17 kilómetros del pueblo la famosa laguna de Guatavita la cual dio origen a la leyenda del dorado.', 'Enseñanza de la historia nativa del lugar, costumbres, rituales, los mitos y leyendas de los primeros habitantes de estas tierras, de los indígenas.\r\nhttp://sendanativa.com/es/'),
(66, 'Lagos Del Siecha Restaurante y Pesca ', 'Sector Paso Hondo, Vda. La Trinidad, Guasca, Cundinamarca', '4.799171, -73.891873', 'Caminar o montar en bicicleta, recorrer los lagos en kayak o bote y pesca.', 'El lugar cuenta con varios tipos de alojamiento, incluyendo cabañas, domos y tiendas de campaña, así como zonas comunes con piscinas, juegos infantiles y áreas para hacer fogatas.\r\n\r\nUna de las principales atracciones del lugar son los lagos, que están rodeados por senderos.', 'Se pueden observar frailejones, lagunas, lagunetas y quebradas; patos de páramo, águilas, colibríes, horneros, azulejos, tángaras.\r\nhttps://www.lagosdelsiecha.com/'),
(67, 'Senderos del Sisga', 'Senderos del Sisga, Chocontá, Cundinamarca', '5.050942, -73.703780', 'Zona de Camping\r\n\r\nAlquiler Kit Camping\r\nPicnic, Asados, Pasadía, Senderismo, Ciclomontañismo, Eventos y Avistamiento de Aves Colibríes.', 'Un espacio donde poder compaginar el deporte y la aventura con un entorno ecológico,  disfrutar de paisajes y riquezas naturales, y al mismo tiempo incentivar conciencia ecológica, aportando al cuidado del medio ambiente', 'Es posible observar especies como el pino ciprés y el pino pátula representativos del bosque alto andino.\r\nhttps://www.senderosdelsisga.com/ '),
(68, 'Cascada El Escobo', 'Vereda La Vistosa Vereda El Tigre, Vergara, Cundinamarca', '5.114022, -74.364311', 'Senderismo, canyonnering, visita a piscina natural, torrentismo, transporte y almuerzo, y recorrido al pueblo de Vergara', 'Ubicado en Vergara un municipio con una belleza inmensa, hace parte de la llamada Región Gualiva, y aunque es un poco frío, ofrece comida deliciosa, deportes extremos y turismo ecológico.', 'Antes de llegar a la casada principal (el Escobo) tendrá que pasar por dos pequeñas cascadas y una piscina natural.\r\nhttps://www.sitiosturisticoscolombia.com/cascada-el-escobo/'),
(69, 'Pacho Aventura', 'Cl. 6 #17-92 #17-2 a, Pacho, Cundinamarca', '5.130199, -74.157249', 'Avistamiento de aves y caminatas-', 'Agencia de tours ecológicos encargados de hacer de tu viaje a Pacho una experiencia memorable en contacto con la naturaleza', 'Observación de aves como elTangara carafuego​, el Carpintero real, Colibrí colihabano, el Halcón murcielaguero​  y el Vencejo acollarado. https://www.instagram.com/pacho.aventura/?hl=es'),
(70, 'Camino Real La mesa ', 'La mesa, Cundinamarca', '4.547379, -74.536511', 'Caminatas y recorridos ecológicos.', 'Hace parte de la red de vías que funcionaron desde la época de la colonia como rutas de intercambio comercial y de conexión entre las poblaciones.', 'El recorrido se inicia desde la zona urbana del municipio transitando por caminos de vereda, caminos reales de piedra y realizando algunos pasos por la ladera del río.\r\nhttps://awali.com.co/destino/caminatas/camino-real-de-la-mesa/ '),
(71, 'Reserva Biológica El Encenillo', 'Guasca, Cundinamarca', '4.794789, -73.908675', 'Observación de fauna y flora, Avistamiento de aves, Siembra de árboles, Pícnic, Senderismo, Ciclomontañismo.', 'La importancia de la Reserva Biológica Encenillo radica en que allí se encuentran relictos naturales de bosques alto andinos de encenillo.', 'Especies vegetales típicas del bosque de encenillo son las orquídeas, bromelias y briófitas. La reserva es un refugio para la fauna representada en mamíferos como coatíes, armadillos, zorros de páramo y numerosas especies de aves residentes y migratorias.\r\nhttps://natura.org.co/reservas/reserva-biologica-el-encenillo/'),
(72, 'Parque Natural Montaña del Oso', 'Chía, Cundinamarca', '4.829793, -74.013705', 'Avistamiento de flora y fauna, recorridos, rappel, escalada, eventos sociales, corporativos e investigaciones.', 'El lugar, es un espacio propicio para el avistamiento de flora y fauna propia del ecosistema. ', 'https://turismo.chia-cundinamarca.gov.co/2020/02/02/blind-climber-ascends-old-man-of-hoy/'),
(73, 'Ecoparque Nukasa', 'Zipaquirá, Cundinamarca', '5.027991, -74.014044', 'Pasadía, Avistamiento de aves, Talleres ambientales, Recreación, Siembra de árboles, Camping.', 'Ecoparque único en las cercanías de Zipaquirá. Tiene un bosque altoandino y un subpáramo muy conservado lo que permite una experiencia transformadora y diferente a nuestros visitantes.', 'Actualmente contamos con 8 senderos, alrededor de los elementos esenciales (aire, tierra, agua y fuego) y el avistamiento de aves. También tenemos producción apícola y pistas de downhill.\r\nhttps://retos.co/ecosistema/comunidades/14/'),
(74, 'Peña de Juaica', 'Km 7 via tenjo, Tabio, Cundinamarca', '4.905417, -74.129441', 'Caminata, avistamiento de aves y mamiferos ', 'Esta montaña guarda diversas leyendas, se dice que desde la cima de la peña muchos indígenas decidieron suicidarse gracias al sometimiento y maltrato por parte de los españoles. ', 'Conocida desde la antigüedad por los muiscas y chibchas, tribus precolombinas que habitaron la región hace varios cientos de años, la Peña de Juaica era el punto de convergencia perfecto en el que realizar un encuentro directo con la naturaleza era casi obligado.\r\nhttps://parchexbogota.com/articulo/la-pena-de-juaica-la-montana-del-misterio/'),
(75, 'Finca el Tinto', 'finca El Tinto, Vereda La Libertad, La Vega, Cundinamarca', '4.955921, -74.332672', 'Recorrido', 'Todo el proceso culmina en una catación y conociendo los metodos y formas de preparar el mejor café de colombia', '\r\nhttps://finca-el-tinto.negocio.site/?utm_source=gmb&utm_medium=referral'),
(76, 'Parque Embalse El Hato', 'Via Hato, Carmen de Carupa, Cundinamarca', '5.303198, -73.905324', 'Ecoturismo, pesca deportiva, deportes acuáticos. ', 'Una hacienda en medio de un embalse rodeado de jardines y zonas verdes. ', 'En la reserva natural se encuentra gran diversidad de flora y fauna.\r\nhttp://www.colparques.net/HATO#aceptar'),
(77, 'Reserva Natural Paraíso Andino', 'Km 12.5, Vía La Vega - Sasaima, Cundinamarca', '4.951936, -74.371390', 'EcoGlamping, caminatas ecológicas', 'Es un espacio natural para el aprendizaje, el descanso, la contemplación y la reconexión con la naturaleza. ', 'https://www.instagram.com/reservaparaisoandino/?hl=es'),
(78, 'Termales los Volcanes', 'Choachí, Cundinamarca', '4.549843, -73.917663', 'Camping.', 'El lugar propicio para conectar con la naturaleza; un espacio especial donde encuentras aguas termales disponibles para la revitalización de tu mente y tu cuerpo.', 'Cuenta con cuatro piscinas de agua termal, agua Mineromedicinal.\r\nhttps://termaleslosvolcanes.com/'),
(79, 'Salto de las Monjas', 'El Ocaso-Cachipay, Cachipay, La Mesa, Cundinamarca', '4.690426, -74.440391', 'Caminatas por senderos.', 'La caminata Salto de Las Monjas es una espectacular caída de treinta metros de altura ubicada entre los municipios de Cachipay y La Mesa. ', 'https://caminatasalairelibre.com/destinos/salto-de-las-monjas/'),
(80, 'Farallones De Sutatausa', 'Sutatausa, Cundinamarca', '5.229958, -73.834828', 'Senderismo, escalar, acampar.', 'Los Farallones De Sutatausa son una formación rocosa.', 'https://senderosyrutas.net/senderismo-farallones-de-sutatausa-colombia/'),
(81, 'Parque Ecoturístico Puente Sopo', 'Sopó, Cundinamarca', '4.936581, -73.983028', 'biciCAR, picnic, caminatas.', 'Parque ecoturístico.', 'https://parques.car.gov.co/PaginaWeb/DetalleParque.aspx'),
(82, 'Cerro del Majui', 'Cota, Cundinamarca', '4.806248, -74.121785', 'Caminatas ecológicas, ', 'El cerro del Majuy se encuentra en los que en la antigüedad fueran los territorios del cacique muisca, era considerado uno de sus sitios sagrados, en la actualidad es protegido por las comunidades muiscas que habitan la zona en la actualidad.', 'https://awali.com.co/destino/caminatas/cerro-del-majuy/'),
(83, 'Páramo Verjón', 'km 15.5, Choachi - Bogotá, Choachí, Cundinamarca', '4.565445, -74.005747', 'Caminatas. ', 'Se recorrerá parte del páramo, iremos hasta llegar a la Laguna de Teusacá ,una de las 5 lagunas sagradas de los Muiscas.', 'https://ecoglobalexpeditions.com/caminata-ecologica-laguna-del-verjon/'),
(84, 'Aves Internacionales Colombia', 'Kilometro 4 Agua de Dios - Nilo, 4°21\'03.4\"N 74°39\'05.4\"W, Vereda Belén de Malachí, Agua de Dios -Nilo, Cundinamarca', '4.351577, -74.651368', 'Caminata.', 'Aves Internacionales Colombia es una organización sin ánimo de lucro, que enfoca sus esfuerzos en el estudio, conservación y monitoreo de aves residentes y migratorias en el Neotrópico.', 'https://www.facebook.com/manadulcereservanatural/'),
(85, 'Salto de Versalles', '56, Guaduas, Cundinamarca', '5.123651, -74.597592', 'Caminata', 'El Salto de Versalles es una cascada de agua de un poco más de 40 metros de altura que se produce por la unión de los ríos San Francisco, El Guadual y Limonar. ', 'https://baquianos.com/es/blog/salto-de-versalles-como-llegar'),
(86, 'Cerro el Tablazo', 'Cra. 85 #8899, Bogotá, Supatá, Cundinamarca', '5.012235, -74.204242', 'Caminata', 'Cerro El Tablazo, es una icónica e imponente montaña ubicada en el municipio de Subachoque, a solo una hora de Bogotá. Su cima se alza por encima de los 3.400 metros sobre el nivel del mar. ', 'En esta caminata ecológica tendrás la combinación perfecta entre la tranquilidad del páramo, y la exuberancia bosque alto andino. \r\nhttps://caminatasalairelibre.com/destinos/cerro-el-tablazo/'),
(87, 'Periland Eco Park', 'La Naveta, Cajicá, El Tejar, Cajicá, Cundinamarca', '4.955881, -74.018778', 'Senderismo, observación de especies endémicas, avistamiento de aves, ', 'es una iniciativa de la Fundación Bosques Verdes, entidad que se ha dedicado desde el año 2015 a conectar familias, colectivos, amigos y sus mascotas con la naturaleza por medio de la educación ambiental. ', 'https://www.perilandecoparque.com/'),
(88, 'Finca Cafetera la Esmeralda', 'Cl. 2, Ubaque, Cundinamarca', '4.4941256, -73.9185005', 'Caminata.', 'La Esmeralda es una finca familiar que desde el 2009 se dedica a  cultivar y procesar café de excelente calidad.', 'https://fincalaesmeraldaub.wixsite.com/fincalaesmeralda'),
(89, 'Parque Ecológico Jerico ', 'Km 33 Autopista Medellín, La Vega, Cundinamarca', '4.911722, -74.296696', 'Caminatas.', 'Parque con vistas hemosas,\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'https://www.facebook.com/parquejerico/?locale=es_LA'),
(90, 'Salto de los Micos', '50, Villeta, Cundinamarca', '5.017715, -74.478932', 'Caminata.', 'Este destino turístico es una maravilla de Villeta, se trata de 7 imponentes cascadas, cada una con características diferentes y con su pozo propio.', 'https://www.sitiosturisticoscolombia.com/salto-de-los-micos-villeta/'),
(91, 'Desierto de Checua', '44VW+JW, Nemocón, Cundinamarca', '5.132712, -73.867140', 'Caminata.', 'Tour de las Orquídeas Colombianas, Birding & Birdwatching en el Tour Andino. ', 'https://www.facebook.com/ForestOfOrchids/?paipv=0&eav=AfZBVMeySUIKqyY8jpzJG_XXV6zK09ieK60JD7HnRathMTt7W9_a5QkVM1YFTTIL2pw&_rdr'),
(92, 'Cerro de Quinini:', '252230, Tibacuy, Cundinamarca', '4.328529, -74.497311', 'Caminata.', 'La región corresponde al antiguo territorio indígena de los Panches, de cuya civilización hay muestras en los petroglifos o arte rupestre y entierros funerarios dispersos en la zona.', 'https://www.roadtrip.travel/roadtrips/caminata-al-cerro-de-quinini-montana-sagrada-de-la-luna'),
(93, 'Parque Verde Agua', 'Hda cimitarra, Fusagasugá, Cundinamarca', '4.360785, -74.335350', 'Caminata', 'Quininí hace referencia a “Montaña sagrada de la Luna ó Diosa de la Luna\", es lo que significa en lengua de las comunidades indígenas que allí habitaron. ', 'https://www.facebook.com/parqueverdeyagua/?locale=es_LA'),
(94, 'Kombai Park Montearroyo', 'Parque Tématico de Aventura, Km 30 Via, Bogotá-La Vega, La Vega', '4.899196, -74.310429', 'Caminata.', 'En un terreno grandioso cuya topografía nos permite entregarte grandes opciones de diversión y ocupación de tu tiempo en familia.', 'https://kombaipark.com/nosotros/'),
(95, 'Parque Monarca', '250208, Tenjo, Cundinamarca', '4.855989, -74.095044', 'Caminata', 'Es un parque para toda la familia, donde puedes realizar eventos especiales mientras disfrutas de la tranquilidad de un ambiente sano, podrás observar diferentes animales de granja y otros como son aves silvestres y diferentes insectos', 'https://parque-monarca.negocio.site/#summary'),
(96, 'Parque Ozagua', 'Hacienda Santa Ana Frente a la escuela Perico, Sibaté, Cundinamarca', '4.462801, -74.265305', 'Caminata avistamiento entornos naturales.', 'Parque ecológico que brinda espacios formativos, recreativos y educativos, para aquellos que buscan experiencias significativas en entornos naturales. ', 'https://parqueozagua.com/nosotros'),
(97, 'Cañón de la Lechuza', 'Suesca, Cundinamarca', '5.103291, -73.758741', 'Senderismo, canotaje.', 'La caminata se puede hacer por dos vías: por el filo de la montaña o por el nivel del río. Ambos caminos se conectan en la orilla del lago en donde propios y visitantes dedican sus horas a la práctica del canotaje e incluso, como un balneario refrescante. ', 'https://viajaporcolombia.com/sitios-turisticos/cundinamarca/canon-de-la-lechuza_260/');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `lugares`
--
ALTER TABLE `lugares`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `lugares`
--
ALTER TABLE `lugares`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=98;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
